### PR TITLE
Added genome build ref hg19 to output VCFs

### PR DESCRIPTION
**Pull request by Graeme-Smith**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Graeme-Smith)

___
*[Mokaonc.txt, line 77 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1c0IZ-BWZnS1mMfzQ:-MT1c0IZ-BWZnS1mMfzR:b-8593qn) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/Mokaonc.txt#L77)):*
> ```
> rename
> ```
mv?
___
*[Mokaonc.txt, line 78 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1cNoT25PMn4uNhrr4:-MT1cNoT25PMn4uNhrr5:brijq2t) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/Mokaonc.txt#L78)):*
> ```vimhelp
>                   \"s/#CHROM/##REFERENCE=hg19\\n#CHROM/\"
>                   $vcf; done; rename
>                   's/.vardict.vcf/.congenica.vardict.vcf/'
> ```

does this changes the file name/suffix? Does it change the output folder?
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1c5vr2ERnppCtprjf:-MT1c5vr2ERnppCtprjg:bb7qbb3) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/README.md#L4)):*
> ```Markdown
> 
> ## V1.6
> Added the genome build hg19 to the ouput VCF headers using Swiss Army Knife app.  Vardict vcfsd now go into ./temp_vcf while the output with the build meta data goes into ./congenica_vcf folder.
> ```

vcfs
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1cCQe2sDiv5e5QmjC:-MT1cCQe2sDiv5e5QmjD:butanmd) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/README.md#L4)):*
> ```
> /temp_vcf
> ```
is this captured in the dx describe output?

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @aledj2)

___
*[Mokaonc.txt, line 77 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1c0IZ-BWZnS1mMfzQ:-MT7AWW_DjxQGhM-L8zG:bn56bh4) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/Mokaonc.txt#L77)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> rename
> ```
mv?
</blockquote></details>

Refactored code into a separate shell script, no longer using rename command.  mv needed because of the -i sed flag amending the files in place, hence the workflow was not detecting them as output that needed uploading at the end of the workflow.
___
*[Mokaonc.txt, line 78 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1cNoT25PMn4uNhrr4:-MT7980g0SZRi3jhGSYO:bmscywj) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/Mokaonc.txt#L78)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

does this changes the file name/suffix? Does it change the output folder?
</blockquote></details>

I've not changed the suffix in the latest refactor, the vpVCFs are output in a separate folder ./amplivar_output/vcf/refheader_vcf/ while the vcf without the ref header goes in temp_vcf/output.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1c5vr2ERnppCtprjf:-MT79lCh9gqmxgYDaleQ:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/README.md#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

vcfs
</blockquote></details>

Done.
___
*[README.md, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MT1cCQe2sDiv5e5QmjC:-MT7Bk8X3cTsSS7DvY6P:bftt5vl) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/259a5f7c407220c318c6b066454a43473f06c590/README.md#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> /temp_vcf
> ```
is this captured in the dx describe output?
</blockquote></details>

the dx describe output does not appear to capture this - I have added this info to the README if that is sufficient?

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[add_ref_build_to_vcf.sh, line 6 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGLJ245cPoI4o9XZDh:-MTGLJ245cPoI4o9XZDi:b-mxed7x) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/add_ref_build_to_vcf.sh#L6)):*
> ```Shell
>     do sed -i "s/#CHROM/##REFERENCE=hg19\n#CHROM/" "$vcf"
> done
> mv ./*dict.vcf ./amplivar_output/vcf/refheader_vcf/
> ```

could we rename this script with the version number
___
*[Mokaonc.txt, line 10 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGKdUnE9bez41iQJcJ:-MTGKdUnE9bez41iQJcK:b4xyuja) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/Mokaonc.txt#L10)):*
> ```vimhelp
> Visibility          visible
> Types               -
> Properties          github release=v1.5
> ```

can you update this please (through the UI in Nexus)
___
*[Mokaonc.txt, line 81 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGKzo52VUIbpnseSyC:-MTGKzo6EfVHi5CQqsF4:bf6zh5n) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/Mokaonc.txt#L81)):*
> ```vimhelp
>                   "file-G0VGyqQ0GfYYbxYZG6fBvk55"}])]
>                     [stage-G0KYx8Q0GfYvbVg49bYf9p9g.cmd (string,
>                   default="bash add_ref_build_to_vcf.sh")]
> ```

could we add a version number to the bash script please?
___
*[README.md, line 4 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNRFj5jHQuH9vuyor:-MTGNRFj5jHQuH9vuyos:bz2dldu) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L4)):*
> ```Markdown
> 
> ## V1.6
> Added the genome build hg19 to the ouput VCF headers using Swiss Army Knife app and the shell script Add_ref_to_vcf which is version controlled in thisrepo.  Vardict vcfs go into ./temp_vcf, while the output from vardict with the build reference meta data goes into /amplivar_output/vcf/refheader_vcf/ for consistency with previous versions.
> ```

verison number
___
*[README.md, line 6 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNU_o4ND7f_69KTrU:-MTGNU_o4ND7f_69KTrV:b-givm7e) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L6)):*
> ```Markdown
> Added the genome build hg19 to the ouput VCF headers using Swiss Army Knife app and the shell script Add_ref_to_vcf which is version controlled in thisrepo.  Vardict vcfs go into ./temp_vcf, while the output from vardict with the build reference meta data goes into /amplivar_output/vcf/refheader_vcf/ for consistency with previous versions.
> 
> ## add_ref_build_to_vcf.sh
> ```

version number
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNckmBMD1Mnbu-xV-:-MTGNckmBMD1Mnbu-xV0:b-9mmnfm) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L7)):*
> ```Markdown
> 
> ## add_ref_build_to_vcf.sh
> This script is designed to be called by the Swiss Army app as part of the MokaONC 1.6 pipeline. It uses the bash tool sed to add a line to any VCF headers specifying the reference as hg19, the reference used by the current MokaONC 1.6 pipeline. This is required for small panels being uploaded to Congenica as the panels must be above a certain size in order for there to be enough data for the platform to infer the build.
> ```

QCI not congenica
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNitqELkdqHHdEti9:-MTGNitqELkdqHHdEtiA:b-9978qq) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L7)):*
> ```Markdown
> 
> ## add_ref_build_to_vcf.sh
> This script is designed to be called by the Swiss Army app as part of the MokaONC 1.6 pipeline. It uses the bash tool sed to add a line to any VCF headers specifying the reference as hg19, the reference used by the current MokaONC 1.6 pipeline. This is required for small panels being uploaded to Congenica as the panels must be above a certain size in order for there to be enough data for the platform to infer the build.
> ```

infers the build if not stated in the header or at the point of upload

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @aledj2 and @Graeme-Smith)

___
*[Mokaonc.txt, line 81 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGKzo52VUIbpnseSyC:-MTGczts9wKy8JYRzsOQ:b-yev98m) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/Mokaonc.txt#L81)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could we add a version number to the bash script please?
</blockquote></details>

Added add_ref_build_to_vcf_v1.0.0.sh
___
*[README.md, line 6 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNU_o4ND7f_69KTrU:-MTGfKP53Ph0CujvuN0k:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

version number
</blockquote></details>

Done.
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNckmBMD1Mnbu-xV-:-MTGd7MaExfk3mfzcd0z:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L7)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

QCI not congenica
</blockquote></details>

Done.
___
*[README.md, line 7 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNitqELkdqHHdEti9:-MTGdIPPBf1e3YlXxEFo:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L7)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

infers the build if not stated in the header or at the point of upload
</blockquote></details>

Done.
___
*[add_ref_build_to_vcf.sh, line 6 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGLJ245cPoI4o9XZDh:-MTGce5iAaNvJIBe7ruD:b-a9ofdp) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/add_ref_build_to_vcf.sh#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could we rename this script with the version number
</blockquote></details>

I've changed the name to add_ref_build_to_vcf_v1.0.0.sh and changed the Swiss army knife app description to add_ref_build_to_vcf_v1.0.0, and have ammended to optional command to bash 
add_ref_build_to_vcf_v1.0.0.sh

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @aledj2)

___
*[Mokaonc.txt, line 10 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGKdUnE9bez41iQJcJ:-MTGo8zYBhsdN-dZFgum:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/Mokaonc.txt#L10)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you update this please (through the UI in Nexus)
</blockquote></details>

Done.
___
*[README.md, line 4 at r4](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5#-MTGNRFj5jHQuH9vuyor:-MTGo7oBAqwo1hPfpErc:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokaonc_workflow/blob/d02bbc04bb55be822db529a08d31000744d89cf1/README.md#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

verison number
</blockquote></details>

Done.

**Review by aledj2 — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaonc_workflow/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
